### ISSUE TITLE
Usuário do lider do grupo

### ISSUE THREAD

**Issue by nukdown** [fga-verival/2019-2Grupo8#1]
Comentem nessa issue o usuário github do lider do grupo 8, que será responsável por dar privilegio para os demais membros neste repositório.

**Comment by Miguel-Alves** [comment]
Miguel-Alves

**Comment by nukdown** [comment]
pronto @Miguel-Alves , só add a galera ai

**Comment by Miguel-Alves** [comment]
Beleza, mas tu tem que me passar a permissão @nukdown
