### ISSUE TITLE
Permissão

### ISSUE THREAD

**Issue by Miguel-Alves** [fga-verival/2019-2Grupo8#2]
Passa a permissão aí @nukdown ! Não consigo adicionar ninguém não

**Comment by aamandafelix** [comment]
@Miguel-Alves, verifique se você consegue visualizar e aceitar seu convite do repositório nesse link
https://github.com/fga-verival/2019-2Grupo8/invitations, pra poder ter as permissões.

**Comment by nukdown** [comment]
Peço perdão @Miguel-Alves , acabei me esquecendo de criar a issue no repositório do seu grupo. Verifiquei aqui e você está com permissão, provavelmente a Amanda deve ter dado. Bom trabalho anyway, qualquer coisa é só marcar!
